package client.net;

import java.net.InetSocketAddress;

/**@Frank
 * 
 * @role: a interface which directly pass the communication events from net layer to view layer,
 * 			there will be no controller layer
 * 
 * 
 * */

public interface CommunicationListener {
	/**
	 * handles the string msg generated by the server's game logic
	 * @param msg
	 */
	public void gameMsg(String msg);
	/**
	 * used display connect success message to user
	 * @param serverAddress
	 */
	public void connected(InetSocketAddress serverAddress);

    /**
     * Called when the local client is successfully disconnected from the server.
     */
    public void disconnected();
}
